project:
  type: website
  output-dir: docs
  
website: 
  title: "The Effectiveness of Esketamine on Depression1 Alleviation with Metabolic Syndrome Based on MMRM"
      
format: 
  html: 
    theme: cosmo
    toc: false
